version: '2'
services:

    $${INSTANCE_NAME}-cache:
      image: fikipollo/pysica
      container_name: $${INSTANCE_NAME}-cache
      depends_on:
        - $${INSTANCE_NAME}-data
      volumes_from:
        - $${INSTANCE_NAME}-data
      ports:
        - "4444:4444"

    $${INSTANCE_NAME}-data:
      image: busybox
      container_name: $${INSTANCE_NAME}-data
      volumes:
        - /data/$${INSTANCE_NAME}-data/logs:/var/log/pysica
        - /data/$${INSTANCE_NAME}-data/conf:/var/www/pysica/conf
