version: '2'
services:

    instance1-cache:
      image: fikipollo/pysica
      container_name: instance1-cache
      ports:
        - "4444:4444"
      volumes:
        - /data/instance1-data/logs:/var/log/pysica
        - /data/instance1-data/conf:/var/www/pysica/conf
